package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const sampleConfig = `# Automatically generated.  DO NOT EDIT THIS FILE!
    search --set=drive1 --fs-uuid 640F-693F
    set default=0

menuentry "NixOS" --class nixos --unrestricted {
  linux ($drive1)//kernels/aaa-linux-7.1.5-bzImage init=/nix/store/sys-new/init loglevel=4
  initrd ($drive1)//kernels/bbb-initrd-linux-7.1.5-initrd
}

menuentry "NixOS - Configuration 123 (2026-08-09)" --class nixos {
  linux ($drive1)//kernels/aaa-linux-7.1.5-bzImage init=/nix/store/sys-new/init loglevel=4
  initrd ($drive1)//kernels/bbb-initrd-linux-7.1.5-initrd
}

menuentry "NixOS - Configuration 122 (2026-08-09)" --class nixos {
  linux ($drive1)//kernels/ccc-linux-7.0.8-bzImage init=/nix/store/sys-old/init
  initrd ($drive1)//kernels/ddd-initrd-linux-7.0.8-initrd
}
`

func writeConfig(t *testing.T) (bootDir, cfg string) {
	t.Helper()
	bootDir = t.TempDir()
	if err := os.MkdirAll(filepath.Join(bootDir, "grub"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(bootDir, "kernels"), 0o755); err != nil {
		t.Fatal(err)
	}
	cfg = filepath.Join(bootDir, "grub", "grub.cfg")
	if err := os.WriteFile(cfg, []byte(sampleConfig), 0o644); err != nil {
		t.Fatal(err)
	}
	return bootDir, cfg
}

func touch(t *testing.T, dir string, names ...string) {
	t.Helper()
	for _, n := range names {
		if err := os.WriteFile(filepath.Join(dir, n), []byte("x"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

func TestEspPath(t *testing.T) {
	cases := map[string]string{
		"($drive1)//kernels/abc": "/kernels/abc",
		"(hd0,1)/kernels/abc":    "/kernels/abc",
		"//kernels/abc":          "/kernels/abc",
		"kernels/abc":            "/kernels/abc",
		"($drive1)//":            "",
		"($drive1":               "",
	}
	for in, want := range cases {
		if got := espPath(in); got != want {
			t.Errorf("espPath(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestParseGrubConfigDeduplicates(t *testing.T) {
	_, cfg := writeConfig(t)
	refs, err := parseGrubConfig(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if len(refs) != 4 {
		t.Fatalf("got %d unique files, want 4", len(refs))
	}
	if n := len(refs[0].entries); n != 2 {
		t.Errorf("the shared kernel is referenced by %d entries, want 2", n)
	}
}

func TestDefaultSystemPath(t *testing.T) {
	_, cfg := writeConfig(t)
	got, err := defaultSystemPath(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if got != "/nix/store/sys-new" {
		t.Errorf("got %q, want /nix/store/sys-new", got)
	}
}

func TestMenuEntryCountSkipsDefault(t *testing.T) {
	_, cfg := writeConfig(t)
	n, err := menuEntryCount(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if n != 2 {
		t.Errorf("got %d generation entries, want 2", n)
	}
}

func TestCheckKernelsDetectsMissingDefault(t *testing.T) {
	bootDir, cfg := writeConfig(t)
	touch(t, filepath.Join(bootDir, "kernels"),
		"ccc-linux-7.0.8-bzImage", "ddd-initrd-linux-7.0.8-initrd")

	e := &env{bootDir: bootDir, cfgPath: cfg}
	e.refs, e.refsErr = parseGrubConfig(cfg)

	c := checkKernels(e)
	if c.Status != StatusFail {
		t.Fatalf("status = %q, want fail", c.Status)
	}
	if !strings.Contains(strings.Join(c.Details, "\n"), "grub> prompt") {
		t.Error("a broken default entry should be called out explicitly")
	}
}

func TestCheckOrphansFindsUnreferencedFiles(t *testing.T) {
	bootDir, cfg := writeConfig(t)
	kernels := filepath.Join(bootDir, "kernels")
	touch(t, kernels,
		"aaa-linux-7.1.5-bzImage", "bbb-initrd-linux-7.1.5-initrd",
		"ccc-linux-7.0.8-bzImage", "ddd-initrd-linux-7.0.8-initrd",
		"zzz-linux-6.12.0-bzImage")

	e := &env{bootDir: bootDir, cfgPath: cfg}
	e.refs, e.refsErr = parseGrubConfig(cfg)

	c := checkOrphans(e)
	if c.Status != StatusWarn {
		t.Fatalf("status = %q, want warn", c.Status)
	}
	if c.Data["files"] != 5-4 {
		t.Errorf("found %v orphans, want 1", c.Data["files"])
	}
}

func TestQuietOutputIsOneLine(t *testing.T) {
	r := buildReport("test", []Check{
		ok("a", "first").detail("hidden"),
		ok("b", "second").detail("hidden too"),
	})
	var buf bytes.Buffer
	r.writeText(&buf, false)

	lines := strings.Split(strings.TrimSpace(buf.String()), "\n")
	if len(lines) != 1 {
		t.Fatalf("quiet output has %d lines, want 1:\n%s", len(lines), buf.String())
	}
	if strings.Contains(buf.String(), "hidden") {
		t.Error("details should stay hidden when everything passed")
	}
}

func TestVerboseOutputShowsEverything(t *testing.T) {
	r := buildReport("test", []Check{ok("a", "first").detail("shown")})
	var buf bytes.Buffer
	r.writeText(&buf, true)
	if !strings.Contains(buf.String(), "shown") {
		t.Error("verbose output should include details")
	}
}

func TestWarningsSurfaceWithoutVerbose(t *testing.T) {
	r := buildReport("test", []Check{
		ok("a", "quiet one").detail("hidden"),
		warn("b", "look at this").detail("visible"),
	})
	var buf bytes.Buffer
	r.writeText(&buf, false)
	out := buf.String()

	if strings.Contains(out, "hidden") {
		t.Error("passing checks should stay hidden")
	}
	if !strings.Contains(out, "visible") {
		t.Error("warning details should be shown")
	}
}

func TestReportStatusPrecedence(t *testing.T) {
	cases := []struct {
		checks []Check
		want   Status
		safe   bool
	}{
		{[]Check{ok("a", "x")}, StatusOK, true},
		{[]Check{ok("a", "x"), skip("b", "y")}, StatusOK, true},
		{[]Check{ok("a", "x"), warn("b", "y")}, StatusWarn, true},
		{[]Check{warn("a", "x"), fail("b", "y")}, StatusFail, false},
	}
	for i, c := range cases {
		r := buildReport("test", c.checks)
		if r.Status != c.want || r.SafeToReboot != c.safe {
			t.Errorf("case %d: status %q safe %v, want %q %v",
				i, r.Status, r.SafeToReboot, c.want, c.safe)
		}
	}
}

func TestJSONIsValidAndComplete(t *testing.T) {
	r := buildReport("test", []Check{
		ok("a", "fine"),
		warn("b", "hmm").detail("why").data("bytes", 42),
	})
	var buf bytes.Buffer
	if err := r.writeJSON(&buf); err != nil {
		t.Fatal(err)
	}

	var back Report
	if err := json.Unmarshal(buf.Bytes(), &back); err != nil {
		t.Fatalf("output is not valid JSON: %v", err)
	}
	if back.Status != StatusWarn || len(back.Checks) != 2 {
		t.Errorf("round trip lost information: %+v", back)
	}
	if back.Checks[1].Data["bytes"] != float64(42) {
		t.Errorf("attached data did not survive: %v", back.Checks[1].Data)
	}
}

func TestHuman(t *testing.T) {
	cases := map[uint64]string{
		512: "512 B", 1024: "1.0 KiB", 1536: "1.5 KiB",
		1048576: "1.0 MiB", 6402843443: "6.0 GiB",
	}
	for in, want := range cases {
		if got := human(in); got != want {
			t.Errorf("human(%d) = %q, want %q", in, got, want)
		}
	}
}

func TestPlural(t *testing.T) {
	if got := plural(1, "file", "files"); got != "1 file" {
		t.Errorf("got %q", got)
	}
	if got := plural(0, "file", "files"); got != "0 files" {
		t.Errorf("got %q", got)
	}
	if got := plural(7, "file", "files"); got != "7 files" {
		t.Errorf("got %q", got)
	}
}
